### ISSUE TITLE
Retry layer

### ISSUE THREAD

**Issue by MTRNord** [geofmureithi/apalis-amqp#1]
Hi,

I am not sure if it is needed or not since I am new to rabbitmq, but the base package apalis has a retry layer which doesn't work with this crate due to missing implementations. Is there any chance to support that layer or is this happening automatically on error already?

**Comment by MTRNord** [comment]
Thanks :) I am in no rush so take you time :) it was just something I observed while using the crate

**Comment by geofmureithi** [comment]
Closed by https://github.com/geofmureithi/apalis-amqp/pull/14
